
<?
$signatures = $this->driver->getLocalSignature();
if ($this->driver->isAvailableInTuebingen() || !empty($signatures)) {
    echo "<tr>";
    echo "<th>";
    echo $this->transEsc('Availability') . ":";
    echo "</th>";
    echo "<td>";
    echo $this->transEsc('Available in Tubingen') . ".<br>";
    foreach ($this->driver->getLocalSignature() as $signature) {
        echo $this->escapeHtml($signature) . "<br>";
    }
    echo "</td>";
    echo "</tr>";
}
?>
