<tr>
    <th>
        <?= $this->transEsc('Availability') . ":"; ?>
    </th>
    <td>
        <?php
        $signatures = $this->driver->getLocalSignature();
        if ($this->driver->isAvailableInTuebingen() || !empty($signatures)) {
            echo $this->transEsc('Available in Tubingen') . ".<br>";
            foreach ($this->driver->getLocalSignature() as $signature) {
                echo $signature . "<br>";
            }
        } ?>
    </td>
</tr>
