<?
    $formats = $this->driver->getFormats();
    if (empty($formats)):
?>
        <span class="iconlabel <?=$this->record($this->driver)->getFormatClass("Unknown")?>"><?=$this->transEsc("Unknown")?></span>
<?
    else:
    foreach ($formats as $format): ?>
        <span class="iconlabel <?=$this->record($this->driver)->getFormatClass($format)?>"><?=$this->transEsc($format)?></span>
<?
    endforeach;
    endif;
?>
