      <? $formats = $this->driver->getFormats(); if (!empty($formats) && ($formats[0] == "Article" || $formats[0] == "Journal" || $formats[0] == "Article")): ?>
        <tr>
          <th>Journals Online &amp; Print:</th>
          <td><div style="color:grey" id="jop_place_holder"><?=$this->transEsc("Loading")?>...</div></td>
        </tr>
        <script type="text/javascript" language="javascript">
          var genre = ("<?=$formats[0]?>" == "Article" ? "article" : "journal");
          $.ajax({
            type: "GET",
            url: "<?=$this->url('home') ?>proxy/load?url=http%3A%2F%2Fservices.dnb.de%2Ffize-service%2Fgvr%2Ffull.xml%3Fsid%3Dbib%3Atueb%26issn%3D<?=$this->escapeHtml($this->driver->getCleanISSN())?>%26genre%3D"+genre+"%26pid%3Dclient_ip%253D<?=$_SERVER['REMOTE_ADDR'];?>",
            dataType: "xml",
            success: function(xml) {
              $(document).ready(function() {
                var sURL = null;
                $(xml).find('Result').each(function(index, value) {
                    var state = $(this).attr("state");
                    if (state >= 0 && state <= 3) {
                        sURL = $(value).find('AccessURL').first().text();
			return false;
                    }
                });
                if (sURL != null) {
                    $("#jop_place_holder").each(function() {
                        var text = '<?=$this->transEsc("Available locally or online")?>';
                        $(this).replaceWith('<a href="' + sURL + '">' + text + '.</a>');
                    });
                } else {
                    $("#jop_place_holder").each(function() {
                        $(this).replaceWith('<?=$this->transEsc("Not available")?>.');
                    })
                }
              }); 
            }, // end success
            error: function(xhr, ajaxOptions, thrownError) {
              $("#jop_place_holder").each(function() {
                $(this).replaceWith('Invalid server response. (JOP server down?)');
              })
              if (window.console && window.console.log) {
                console.log("Status: " + xhr.status + ", Error: " + thrownError);
              }
            }
          }); // end ajax
        </script>
      <? endif; ?>
