<?
  // Set page title.
  $this->headTitle($this->translate('Search History'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('History') . '</li>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <?=$this->flashmessages()?>
    <? if ($saveSupported && !empty($this->saved)): ?>
      <h2><?=$this->transEsc("history_saved_searches")?></h2>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => true));?>
    <? endif; ?>

    <h2><?=$this->transEsc("history_recent_searches")?></h2>
    <? if (!empty($this->unsaved)): ?>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => false));?>
      <a href="?purge=true"><i class="fa fa-remove" aria-hidden="true"></i> <?=$this->transEsc("history_purge")?></a>
    <? else: ?>
      <?=$this->transEsc("history_no_searches")?>
    <? endif; ?>
  </div>
</div>