<h1>Ein kriminologisches Beispiel</h1>

<p>Manche Suchen sind komplizierter und eine einfache Suche reicht hierfür nicht aus. Zum Beispiel: Sie wollen nach
    Titeln zur historischen Entwicklung des Resozialisierungsansatzes in <i>Deutschland</i> suchen. Wenn Sie die Suchbegriffe
    <i>Resozialisierung</i> <i>Deutschland</i> mit der Suchbedingung "Mit ALLEN Wörtern" in das Suchfeld eingeben, so erhalten Sie nur
    die Titel, die sich mit der <i>Resozialisierung</i> in <i>Deutschland</i> beschäftigen. Verwenden Sie die Suchbedingung "Mit
    IRGENDEINEM der Wörter", so erhalten Sie auch Titel, die nichts mit dem Resozialisierungsansatz zu tun haben oder
    die sich nicht auf <i>Deutschland</i> beziehen.</p>
<p>Für eine komplexe Suche können Sie weitere Suchfelder hinzufügen (und mit dem rechts befindlichen Kreuz auch wieder
    entfernen). Mit dem Feld "Suchbedingung" können Sie wieder steuern, ob für die Suche alle oder irgendein Begriff
    beachtet werden soll. Für das oben beschriebene Beispiel können Sie die Suche mit den Suchbedingungen folgendermaßen
    lösen:</p>
<ul>
    <li>Fügen Sie in das erste Suchfeld die Begriffe <i>Resozialisierung</i> und <i>Deutschland</i> ein und setzen sie die
        Schaltfläche der Suchbedingung auf "Mit ALLEN Wörtern".
    </li>
    <li>Fügen sie ein weiteres Suchkriterium hinzu und geben Sie dort Geschichte und Entwicklung ein. Setzen sie die
        Suchbedingung auf "Mit IRGENDEINEM Wort".
    </li>
</ul>
<p>Nun erhalten Sie alle Titel, die sich mit <i>Resozialisierung</i> UND <i>Deutschland</i> beschäftigen und dabei entweder über den
    Begriff Geschichte ODER Entwicklung eine Darstellung im Zeitverlauf erwarten lassen.</p>

<h2>Beispiel zur Minimierung der Treffermenge:</h2>
<p>Sollten Sie Begriffe aus einer Treffermenge ausschließen wollen, beispielsweise den Begriff <i>Deutschland</i> aus der
    Treffermenge zu <i>Strafvollzug</i>, so gehen Sie folgendermaßen vor:</p>
<ul>
    <li>Fügen Sie in das erste Suchfeld den Begriff <i>Strafvollzug</i> ein und setzen Sie die Schaltfläche der Suchbedingung
        auf "Mit ALLEN Wörter".
    </li>
    <li>Fügen sie ein weiteres Suchkriterium hinzu und geben Sie dort <i>Deutschland</i> ein. Setzen Sie die Suchbedingung auf
        "OHNE die Wörter".
    </li>
</ul>
<p>Dadurch erhalten Sie die Titel zum Strafvollzug, in denen nicht auch der Begriff <i>Deutschland</i> genannt wird.
<p>Um auch verwandte Begriffe auszuschließen, setzen Sie die Suchoperatoren ein, also beispielsweise:
<p>deutsch*
<p>Über diesen Vorgang schließen Sie auch die Begriffe <i>deutsche</i>, <i>Deutscher</i>, <i>deutsches</i> etc. aus.</p>
<p>Ihre Suche können Sie über die Schaltfläche "Erweiterte Suche bearbeiten“ in der Kopfzeile beliebig verändern. Über
    die "Suchhistorie“ unter den "Suchoptionen“ der Fußzeile können Sie zu einem späteren Zeitpunkt zu Ihren
    Suchvorgängen zurückkehren.</p>
