<h1>Ein kriminologisches Beispiel</h1>

<p>Manche Suchen sind komplizierter und eine einfache Suche reicht hierfür nicht aus. Zum Beispiel: Sie wollen nach
    Titeln zur historischen Entwicklung des Resozialisierungsansatzes in Deutschland suchen. Wenn Sie die Suchbegriffe
    Resozialisierung Deutschland mit der Suchbedingung "Mit ALLEN Wörtern" in das Suchfeld eingeben, so erhalten Sie nur
    die Titel, die sich mit der Resozialisierung in Deutschland beschäftigen. Verwenden Sie die Suchbedingung "Mit
    IRGENDEINEM der Wörter", so erhalten Sie auch Titel, die nichts mit dem Resozialisierungsansatz zu tun haben oder
    die sich nicht auf Deutschland beziehen.</p>
<p>Für eine komplexe Suche können Sie weitere Suchfelder hinzufügen (und mit dem rechts befindlichen Kreuz auch wieder
    entfernen). Mit dem Feld "Suchbedingung" können Sie wieder steuern, ob für die Suche alle oder irgendein Begriff
    beachtet werden soll. Für das oben beschriebene Beispiel können Sie die Suche mit den Suchbedingungen folgendermaßen
    lösen:</p>
<ul>
    <li>Fügen Sie in das erste Suchfeld die Begriffe Resozialisierung und Deutschland ein und setzen sie die
        Schaltfläche der Suchbedingung auf "Mit ALLEN Wörtern".
    </li>
    <li>Fügen sie ein weiteres Suchkriterium hinzu und geben Sie dort Geschichte und Entwicklung ein. Setzen sie die
        Suchbedingung auf "Mit IRGENDEINEM Wort".
    </li>
</ul>
<p>Nun erhalten Sie alle Titel, die sich mit Resozialisierung UND Deutschland beschäftigen und dabei entweder über den
    Begriff Geschichte ODER Entwicklung eine Darstellung im Zeitverlauf erwarten lassen.</p>

<h2>Beispiel zur Minimierung der Treffermenge:</h2>
<p>Sollten Sie Begriffe aus einer Treffermenge ausschließen wollen, beispielsweise den Begriff Deutschland aus der
    Treffermenge zu Strafvollzug, so gehen Sie folgendermaßen vor:</p>
<ul>
    <li>Fügen Sie in das erste Suchfeld den Begriff Strafvollzug ein und setzen Sie die Schaltfläche der Suchbedingung
        auf "Mit ALLEN Wörter".
    </li>
    <li>Fügen sie ein weiteres Suchkriterium hinzu und geben Sie dort Deutschland ein. Setzen Sie die Suchbedingung auf
        "OHNE die Wörter".
    </li>
</ul>
<p>Dadurch erhalten Sie die Titel zum Strafvollzug, in denen nicht auch der Begriff Deutschland genannt wird.
<p>Um auch verwandte Begriffe auszuschließen, setzen Sie die Suchoperatoren ein, also beispielsweise:
<p>deutsch*
<p>Über diesen Vorgang schließen Sie auch die Begriffe deutsche, Deutscher, deutsches etc. aus.</p>
<p>Ihre Suche können Sie über die Schaltfläche "Erweiterte Suche bearbeiten“ in der Kopfzeile beliebig verändern. Über
    die "Suchhistorie“ unter den "Suchoptionen“ der Fußzeile können Sie zu einem späteren Zeitpunkt zu Ihren
    Suchvorgängen zurückkehren.</p>
